#!/usr/bin/perl -w
use strict;
BEGIN { unshift @INC, qw( lib extlib ../../lib ../../extlib plugins/MacLeod/lib ) }
use MT::Bootstrap::CLI App => 'MacLeod::Tool::BlogMerge';

__END__

=head1 NAME

merge-blogs - Transfer content/associations from one blog to another

=head1 VERSION

This documentation refers to merge-blogs version 0.9.0.

=head1 SYNOPSIS

Usage: $0 [options] SRC_BLOG TARGET_BLOG

Options:
    --perms     Migrate user/group associations (i.e. permissions)
    --dryrun    Run through without modifying anything
    --force     Don't prompt for confirmation of actions
    --verbose   Output more progress information
    --man       Output the man page for the utility
    --help      Output this message

Example:   
    cd $MT_HOME
    ./plugins/MacLeod/tools/merge-blogs --dryrun SOURCE_BLOG DEST_BLOG


=head1 DESCRIPTION

A full description of the module and its features.

May include numerous subsections (i.e., =head2, =head3, etc.).

=head1 SUBROUTINES/METHODS

A separate section listing the public components of the module's interface.

These normally consist of either subroutines that may be exported, or methods
that may be called on objects belonging to the classes that the module
provides.

Name the section accordingly.

In an object-oriented module, this section should begin with a sentence (of the
form "An object of this class represents ...") to give the reader a high-level
context to help them understand the methods that are subsequently described.

=head1 DIAGNOSTICS

A list of every error and warning message that the module can generate (even
the ones that will "never happen"), with a full explanation of each problem,
one or more likely causes, and any suggested remedies.

=head1 CONFIGURATION AND ENVIRONMENT

A full explanation of any configuration system(s) used by the module, including
the names and locations of any configuration files, and the meaning of any
environment variables or properties that can be set. These descriptions must
also include details of any configuration language used.

=head1 DEPENDENCIES

A list of all of the other modules that this module relies upon, including any
restrictions on versions, and an indication of whether these required modules
are part of the standard Perl distribution, part of the module's distribution,
or must be installed separately.

=head1 INCOMPATIBILITIES

A list of any modules that this module cannot be used in conjunction with.
This may be due to name conflicts in the interface, or competition for system
or program resources, or due to internal limitations of Perl (for example, many
modules that use source code filters are mutually incompatible).

=head1 BUGS AND LIMITATIONS

This utility does not transfer the following during a merge:

    * Templates and template maps
    * Category and placement records
    * Session records
    * Fileinfo records
    * Records from TheSchwartz-related tables

There are no known bugs in this module.  

If you are having problems installing or using the plugin, please check out 
our general knowledge base and help ticket system at 
[help.endevver.com](http://help.endevver.com).

## Copyright ##

Copyright 2010, Endevver, LLC. All rights reserved.

## License ##

This plugin is licensed under the GPL v2.

# About Endevver #

We design and develop web sites, products and services with a focus on 
simplicity, sound design, ease of use and community. We specialize in 
Movable Type and offer numerous services and packages to help customers 
make the most of this powerful publishing platform.

http://www.endevver.com/

